# Generated by Django 4.0.2 on 2022-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
